### ISSUE TITLE
Puffff. Más errores con las nuevas opciones implementadas.

### ISSUE THREAD

**Issue by ManjiChiba** [AyuntamientoMadrid/consul#1092]
¿Se ha hecho fase de testing?
Madre mia. Esto falla más que una escopeta de feria.
Siento el jarro de agua fría, pero...
Esto tiene más bugs y agüjeros que un juego de Bugisoft.
Empezemos.
El cuadro que aparece "¿Es contenido relacionado SI/NO?" al hacer hover sobre el div, a mi entender, no debería de funcionar así (sólo visible cuando hagamos hover).
![contenidorelacionado](https://user-images.githubusercontent.com/16508522/34362146-6aca5ef4-ea71-11e7-8a8d-a91b4ba13fc0.jpg)

Si no esta visible desde el principio y en todo momento, puede que la gente (como me ha pasado a mi), NO se entere de esta nueva opción (clasificación automátia y desatendida de enlances a otras propuestas).
Es una gran idea, pues permite que el trabajo pase a los usuarios en vez de tenerlo que hacer Administración.
Entiendo que Administración simplemente se limitará a revisar aquellos enlaces que tengan mayoría de NO frente a SI y a borrarlos en dicho caso, ¿es así? (porque sino, siempre se podrán boicotear enlaces a base de que un grupito vote en bloque pq un enlace no corresponde, creo que es imprescindible una supervisión por parte de Administración antes de proceder a su eliminación, y no dejarlo sólo en manos de la arbitrariedad de los usuarios, tal y como se supone que se hace con las marcas arbitrarias de "inapropiada" (espero que estéis repasando las que marco yo, porque son propuestas y usuarios totalmente anti-Ahora Madrid y que se repasen las que me han cascado los de la manada Pepera como Inapropiadas porque no puedo editar los debates mientras permanezca dicha marca).
Por cierto, y hablando del tema de los debates... ¿cómo va el tema?. Hay algunos que NO puedo editarlos (no se si porque están marcados arbitrariamente como inapropiados o por otro motivo, como tiempo de publicación o Cantidad de NOs Vs Si, no hay ninguna explicación por ningun lado al respecto).
También, quería retirar alguno por estar obsoleto (supongo que vendría bien para aligerar el peso de la BBDD), pero NO hay opción de hacerlo para los debates, o, por lo menos, yo no la he visto por ningún lado.
Mas cosas... es lógico (y hasta adecuado) que yo no pueda borrar un enlace puesto por otros usuarios (en una propuesta mia o en la de otro usuario), pero.... ¿tampoco puedo borrar un enlace que YO mismo haya puesto (es que los que puse, los hice como prueba, pensado que luego iba a poder quitarlos, y me he encontrado de que no hay opción para ello).

Más cosas raras.
En algunos enlaces si me aparecen las opciones de SI/NO, pero en otros no aparece nada al hacer hover sobre ellos (y estoy hablando de enlaces propios, de propuestas propias, puestas por mi mismo, no de propuestas de otras personas, puestas por otros usuarios). 😲
![contenidorelacionadohidden](https://user-images.githubusercontent.com/16508522/34362368-30c8adee-ea73-11e7-9b0b-a72d238967dc.jpg)

En cuanto a la reciente nueva opción de adjuntar un fichero .pdf (¿sólo .pdf, no se permiten ni siquiera .doc?, ¿un poco... cutre, ¿no?). La subida bien, pero la visualización (probado en firefox).....
![ficherosadjuntos1](https://user-images.githubusercontent.com/16508522/34362425-b6575bb8-ea73-11e7-9c03-50ee4326facc.jpg)
A mi entender... o bien encima ocupando el 100% del div o si lo ponemos a la izq... no le veo pies ni cabeza a que un botón de "Descargar archivo" ocupe casi todo el ancho (más si lo comparamos con el de "Eliminar") y el que tiene el contenido semántico ocupe lo mismo que el de "Eliminar" ¿5%? y el texto se desborde por los laterales de la caja (supongo que será debido a las prisas por sacarlo adelante).

Por cierto, y a este respecto... creo que si se sube un fichero con espacios en blanco luego dar error al intentar descargarlo (Concretamente Error 404. Not found).
Supongo que porque se utiliza Unix o Linux, pero se debería de indicar al usuario para que lo sepa ANTES de subir el fichero.

**Comment by javierm** [comment]
Hi, @manjichiba! Thank you very much for your comments!

I understand seeing things which don't work as one would expect is indeed very frustrating! However, in order to keep all conversations civilized, I'm afraid I'll have to close this issue. It would be great if you could open a new one with the topics which are still causing unexpected behaviours :thumbsup:! When you do so, please follow our [code of conduct](https://github.com/AyuntamientoMadrid/consul/blob/master/CODE_OF_CONDUCT.md) (which can also be found in [the Spanish version of our code of conduct](https://github.com/AyuntamientoMadrid/consul/blob/master/CODE_OF_CONDUCT_ES.md)). Specifically, please avoid political attacks like "manada Pepera" and try to show empathy towards other community members :wink:.

Sorry for the inconvinience and hope my comment doesn't cause unnecessary conflicts! I'm sure we'd immediately understand each other if we talked face to face, and I understand it's far easier to feel offended when using written communication, so let's try to do our best :trophy:!

P.S. I'm using English in this comment because it's the language we use on GitHub. If necessary, I'll try to translate it to Spanish.
