### ISSUE TITLE
Flaky spec: Admin budget investment mark/unmark visible to valuators

### ISSUE THREAD

**Issue by bertocq** [AyuntamientoMadrid/consul#1194]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 46527

**Failure:**

```
  1) Admin budget investments Mark as visible to valuators Unmark as visible to valuator
     Failure/Error: expect(page).to     have_content investment2.title
       expected to find text "Budget Investment 11 title" in "Language: Decide Madrid VALUATION Admin Notifications Delegation My activity My account Sign out Valuation Participatory budgets Budget 60 - Investment projects Assigned to Manuela353 All headings (0) Filter: Under valuation Valuation finished investments cannot be found ID Title Heading name Actions"
     # ./spec/features/admin/budget_investments_spec.rb:998:in `block (3 levels) in <top (required)>'
  2) Admin budget investments Mark as visible to valuators Mark as visible to valuator
     Failure/Error: expect(page).to     have_content investment1.title
       expected to find text "Budget Investment 12 title" in "Language: Decide Madrid VALUATION Admin Notifications Delegation My activity My account Sign out Valuation Participatory budgets Budget 61 - Investment projects Assigned to Manuela358 All headings (0) Filter: Under valuation Valuation finished investments cannot be found ID Title Heading name Actions"
     # ./spec/features/admin/budget_investments_spec.rb:960:in `block (3 levels) in <top (required)>'
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by iagirre** [comment]
In my experience, this flaky commes from the AJAX call. When I backported this feature to consul, I encountered the flaky and developed a [solution](https://github.com/consul/consul/pull/2342/files#diff-366210ce87db4d5a9d74bc535dfba01fR721):

I added a `wait_for_ajax` function so that Capybara was able to wait until the variable was changed in DB. Sometimes, the test was slow enough to let the AJAX finish before the redirection to the vauators page, but there were cases when the test executed too fast, and the redirection and expectations run before the change of the variable, what makes it crash, because there weren't any visible investments (even if it was checked, it wasn't saved to the DB).

The solution that I founded for this flaky is the one developed in [this PR](https://github.com/AyuntamientoMadrid/consul/pull/1206), but it's still WIP until we get some log reports about the error. If the solution for that PR is valid, it can be applied to this flaky and solve it easily.

**Comment by iagirre** [comment]
Because I know the problem, I can work finding a solution for this.

**Comment by bertocq** [comment]
Mark scenario happened again here https://travis-ci.org/AyuntamientoMadrid/consul/jobs/337982693

**Comment by bertocq** [comment]
Mark scenario happened here https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338095346

**Comment by bertocq** [comment]
mark again https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338257531

**Comment by bertocq** [comment]
mark again at https://travis-ci.org/AyuntamientoMadrid/consul/jobs/338257553

**Comment by iagirre** [comment]
I think this issue can be closed.
The PR related has been merged, but I forgot to add the code to close automatically.

**Comment by javierm** [comment]
I forgot to say I started working on this one (PR #1607 ready for review). It was reopened because the tests were still failing, as noted in a [comment in #1256](https://github.com/AyuntamientoMadrid/consul/pull/1256#issuecomment-402863138).
