### ISSUE TITLE
Flaky spec:  Debates Suggesting debates No found suggestions

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#1429]
# What
Tests that fail randomly are called "flakies", this one seems to be one:

**Randomized seed:** 33793

**Travis failed build:** https://travis-ci.org/AyuntamientoMadrid/consul/jobs/367214243

**Failure:**

```
1) Debates Suggesting debates No found suggestions
     Failure/Error:
       within('div#js-suggest') do
         expect(page).not_to have_content 'You are seeing'
       end
     Capybara::ElementNotFound:
       Unable to find visible css "div#js-suggest"
     # ./spec/features/debates_spec.rb:1094:in `block (3 levels) in <top (required)>
```

# How
- [ ] Explain why the test is flaky, or under which conditions/scenario it fails randomly
- [ ] Explain why your PR fixes it
- [ ] Create a backport PR to consul/consul when the fixing PR is approved

### Random values issues
If the problem comes from randomly generated values, running multiple times a single spec could help you reproduce the failure by running at your command line:
```bash
for run in {1..10}
do
  bin/rspec ./spec/features/budgets/investments_spec.rb:256
done
```

You can also try running a single spec in Travis:
Add option `:focus` to the spec and push your branch to Github, for example:
```ruby
scenario 'Show', :focus do
```

But remember to remove that `:focus` changes afterwards when submitting your PR changes!

### Test order issues
Running specs in the order they failed may discover that the problem is that a previous test sets an state in the test environment that makes our flaky fail/pass. Tests should be independent from the rest.

After executing rspec you can see the seed used, add it as an option to rspec, for example:
`bin/rspec --seed 55638` (check **Randomized seed** value at beginning of issue)

### Other things to watch for
- Time related issues (current time, two time or date comparisons with miliseconds/time when its not needed)
- https://semaphoreci.com/community/tutorials/how-to-deal-with-and-eliminate-flaky-tests

**Comment by javierv** [comment]
Hi @decabeza, do you mind if I have a look at this one? It's failed recently on a [Travis build at consul/consul](https://travis-ci.org/consul/consul/jobs/395938528).

**Comment by decabeza** [comment]
Of course @javierv, all yours! 😉

**Comment by javierv** [comment]
There seems to be a bug in the JavaScript code requesting suggestions. I'm not sure that's what's causing this test to fail, though, since I couldn't make it fail on my machine. I've opened  consul#2708 to fix the bug; let's hope it fixes this problem too!

**Comment by javierv** [comment]
As [shown by Travis](https://travis-ci.org/javierv/consul/jobs/397998342), unfortunately consul#2708 doesn't fix this issue. I'll keep looking.

**Comment by javierv** [comment]
I'm using [a branch](https://github.com/javierv/consul/tree/try_travis_build) to execute and debug only the specs which fail more often. The results of the Travis builds are always the same: the first test which is executed fails 100% of the time, and the other tests pass 100% of the time.

Here are a couple of examples, with debugging times to show how long it takes for each test to process the first request and to process the first AJAX request (sorry the debugging messages are cryptic):

* https://travis-ci.org/javierv/consul/builds/398069992
* https://travis-ci.org/javierv/consul/builds/398074436

The first executed AJAX request always takes much longer than the other ones, and that's why it fails. So far I've no idea why that happens every time Travis runs the specs and never when running them locally; @decabeza do you or anyone else have a clue?

P.S. I think I've been sending dozens of notifications to slack about failing builds. I'm so sorry :anguished:! I've already deactivated them.

**Comment by javierv** [comment]
I've just opened consul#2711 with a possible fix.

**Comment by MariaCheca** [comment]
Closed via https://github.com/consul/consul/pull/2711
