### ISSUE TITLE
Improve recommendations of budget investments 

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#1433]
Background
==

Now there is a "Delegation" link on the header and redirect to: 
`/presupuestos/CURRENT_BUDGET/recommendations/new`

What we need
==

- Change the "Delegation" text to "Recommendations".
- Allow inserting the complete URL for budget investment (not only the ID).
- Translate `ID de proyecto de gasto` label.

Notes
==
- It must be possible to fill it from accepting phase. 
- Not change between phases (even if the proposals become unfeasible).
- Each new budget is reset (the header link should include always the current_budget).

Screenshot
==

![screen shot 2018-04-17 at 17 38 55](https://user-images.githubusercontent.com/631897/38880524-3ced87a2-4266-11e8-8b7d-36c4564223f2.png)

**Comment by bertocq** [comment]
@decabeza If I don't understand wrong... each user can have one "Recommended Investments list" for each Budget (or for all budgets) right? 

It could just work as "whislists" work on amazon or other sites:

- A "Recommended Investments list" view that show all the investments on the list and lets the user remove any of them. (and maybe maintain that bad "insert url/id" form
- A "Recommend Investment" or "Add Investment to my Recommendations list" button at the Investment show page, so instead of copying the url or the id and pasting it on that form... you can just use one click

What do you think?

PS: I know that's how Related Content works, but its awful as well and we should improve it to reduce the user action costs for just simple actions
