### ISSUE TITLE
Accesibilidad & validación HTML

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#725]
Ahora podemos ver la validación del HTML y accesibilidad en:

https://rocketvalidator.com/s/7caa7549-cd7f-43af-b522-97ee646c030c/i

**Comment by decabeza** [comment]
@jaimeiniesta ¿puedes hacer que se ignoren estas urls en el reporte? (redirigen fuera de decide.madrid.es y no tenemos control sobre ellas) 😉 

- https://decide.madrid.es/blog  
- https://decide.madrid.es/users/auth/facebook 
- https://decide.madrid.es/users/auth/twitter

**Comment by jaimeiniesta** [comment]
Esta url redirige al último informe disponible:

https://rocketvalidator.com/opensource/decide-madrid/p

Creo que el tema de las redirecciones externas ya está arreglado, lo
compruebo.

**Comment by jaimeiniesta** [comment]
Esta url redirige al último informe disponible:

https://rocketvalidator.com/opensource/decide-madrid/p

Creo que el tema de las redirecciones externas ya está arreglado, lo
compruebo.

El mar. 21, 2017 18:17, "Alberto" <notifications@github.com> escribió:

@jaimeiniesta <https://github.com/jaimeiniesta> ¿puedes hacer que se
ignoren estas urls en el reporte? (redirigen fuera de decide.madrid.es y no
tenemos control sobre ellas) 😉

   - https://decide.madrid.es/blog
   - https://decide.madrid.es/users/auth/facebook
   - https://decide.madrid.es/users/auth/twitter

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AyuntamientoMadrid/consul/issues/725#issuecomment-288151799>,
or mute the thread

**Comment by jaimeiniesta** [comment]
El tema de las redirecciones externas ya está arreglado, ahora antes de incluir una URL en el informe se comprueba la URL final a la que redirige, y si no está dentro del mismo subdominio inicial, se ignora.

Esto evita que se vean issues que en realidad corresponden a sitios externos, pero como ahora cada URL se tiene que comprobar por si acaso redirige, hace que el scraping sea algo más lento. Para que no tarde tanto, es mejor proporcionar un [sitemap XML](https://rocketvalidator.com/articles/performance-tips) que le de directamente las URLs internas a validar.

**Comment by decabeza** [comment]
Cierro el issue ya que contamos con un informe semanal de **Rocket Validator** 🎉  y trabajamos continuamente en arreglar los fallos/advertencias que van apareciendo.
