### ISSUE TITLE
Incluir entradas del blog en la página de inicio

### ISSUE THREAD

**Issue by decabeza** [AyuntamientoMadrid/consul#727]
Para crear una página de inicio más dinámica y a la vez dar más visibilidad al blog de Decide Madrid (https://diario.madrid.es/decidemadrid/) queremos añadir las últimas entradas a la página de inicio `welcome/index`. 

El blog está desarrollado en Wordpress quizás se podría usar un feed para mostrar las tres últimas entradas con:

- Imagen
- Título de la entrada
- Fecha de creación

Quedaría algo similar a esto:

![welcome_blog](https://cloud.githubusercontent.com/assets/631897/24194560/ccbf7fec-0ef6-11e7-990e-c2de704055ab.jpg)

**Comment by bertocq** [comment]
I'm not very well versed on frontend to do this in a few minutes, but the feed thingie could be done with:
```
require 'rss'
FEED_URL = 'https://diario.madrid.es/decidemadrid/feed/'
last_3_items = RSS::Parser.parse(open(FEED_URL).read, false).items[0..2]
```
And for each item you have a title, content_enconded, pubDate, link... attributes.

Only problem I see to fullfill specs is that the feed doesn't include a link to the image displayed as header of each post, neither it is on the content_encoded attribute... Some modifications at the wordpress code would be needed to avoid hacky scrapping instead of RSS usage.

**Comment by bertocq** [comment]
Seems like wordpress situation is not going to change, neither is possible from our side to improve it... closing!
